'use strict';
/* =====================================================================
   Stand roster — official manga names. Each entry:
   moves / labels / cd   J, K, L abilities (see MOVES in stands.js)
   design                the user's look (DESIGNS in art.js)
   art                   figure spec (standart.js): head, pattern,
                         shoulders, lower ('ghost'|'legs'|'horse'),
                         special ('plane'|'pistols'|'vines'), scale…
   range                 preferred fighting distance for the AI
   ===================================================================== */

const PARTS = {
  3: 'Part 3 — Stardust Crusaders',
  4: 'Part 4 — Diamond is Unbreakable',
  5: 'Part 5 — Golden Wind',
  6: 'Part 6 — Stone Ocean',
  7: 'Part 7 — Steel Ball Run',
  8: 'Part 8 — JoJolion',
};

const STAND_LIST = [
  // ------------------------------------------------------------------ Part 3
  {
    id: 'star_platinum', part: 3, name: 'Star Platinum', jp: 'スタープラチナ', user: 'Jotaro Kujo', design: 'jotaro', pose: 'jotaro',
    color: '#7b5cd6', dark: '#3d2a7a', skin: '#9d8cf0', accent: '#f1c75b', hair: '#1c1030',
    glow: 'rgba(150,120,255,0.9)', aura: 'rgba(140,110,255,0.35)', tint: '#4a3aa8',
    stats: { Power: 'A', Speed: 'A', Range: 'C', Durability: 'A', Precision: 'A', Potential: 'A' },
    cry: 'ORA', timeMover: true,
    moves: { J: 'barrage', K: 'timeStop', L: 'starFinger' },
    labels: { J: 'ORA Rush', K: 'Star Platinum: The World', L: 'Star Finger' },
    cd: { J: 2.0, K: 14, L: 3 },
    tsDur: 3.5, tsCall: 'STAR PLATINUM: THE WORLD!', resumeCall: 'Time resumes.',
    art: { head: 'sp', pattern: 'star', shoulders: 'pad', lower: 'ghost' },
    voice: { pitch: 0.7, rush: 'ora ora ora ora ora ora ora ora' },
  },
  {
    id: 'magicians_red', part: 3, name: "Magician's Red", jp: 'マジシャンズレッド', user: 'Muhammad Avdol', design: 'avdol', pose: 'jotaro',
    color: '#d9542b', dark: '#6e1e0e', skin: '#f08a4a', accent: '#ffcf4a',
    glow: 'rgba(255,120,40,0.95)', aura: 'rgba(255,110,30,0.4)', tint: '#b0401a',
    stats: { Power: 'B', Speed: 'B', Range: 'C', Durability: 'B', Precision: 'C', Potential: 'D' },
    cry: '', range: 120,
    moves: { J: 'firePunch', K: 'crossfire', L: 'redBind' },
    labels: { J: 'Flame Punch', K: 'Crossfire Hurricane', L: 'Red Bind' },
    cd: { J: 1.2, K: 5, L: 7 },
    art: { head: 'mr', pattern: 'flame', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 0.8, rush: '' },
  },
  {
    id: 'hierophant_green', part: 3, name: 'Hierophant Green', jp: 'ハイエロファントグリーン', user: 'Noriaki Kakyoin', design: 'kakyoin', pose: 'kakyoin',
    color: '#3fbf6a', dark: '#16552c', skin: '#7ee89a', accent: '#d8ffe0',
    glow: 'rgba(80,255,140,0.9)', aura: 'rgba(60,220,120,0.35)', tint: '#2a8a4a',
    stats: { Power: 'C', Speed: 'B', Range: 'A', Durability: 'B', Precision: 'C', Potential: 'D' },
    cry: '', range: 240,
    moves: { J: 'emeraldSplash', K: 'emeraldBarrier', L: 'tentacle' },
    labels: { J: 'Emerald Splash', K: '20m Emerald Splash', L: 'Tentacle Lash' },
    cd: { J: 2.2, K: 14, L: 3 },
    art: { head: 'hg', pattern: 'melon', shoulders: 'round', lower: 'ghost', slim: true },
    voice: { pitch: 1.1, rush: '' },
  },
  {
    id: 'silver_chariot', part: 3, name: 'Silver Chariot', jp: 'シルバーチャリオッツ', user: 'Jean Pierre Polnareff', design: 'polnareff', pose: 'polnareff',
    color: '#c9ccd6', dark: '#5a5e70', skin: '#e8eaf2', accent: '#e8c04a',
    glow: 'rgba(230,235,255,0.9)', aura: 'rgba(210,215,240,0.35)', tint: '#7a7e90',
    stats: { Power: 'C', Speed: 'A', Range: 'C', Durability: 'B', Precision: 'B', Potential: 'C' },
    cry: '', range: 70,
    moves: { J: 'barrage', K: 'armorOff', L: 'swordLaunch' },
    labels: { J: 'Rapier Flurry', K: 'Armor Off', L: 'Sword Launch' },
    cd: { J: 1.8, K: 12, L: 3 },
    barrage: { style: 'rapier', reach: 46, radius: 18, dmg: 1.7, cry: 'HORA', finisher: { text: 'SILVER CHARIOT!' } },
    art: { head: 'sc', pattern: 'none', shoulders: 'spike', lower: 'legs', weapon: 'rapier' },
    voice: { pitch: 1.2, rush: '' },
  },
  {
    id: 'hermit_purple', part: 3, name: 'Hermit Purple', jp: 'ハーミットパープル', user: 'Joseph Joestar', design: 'joseph', pose: 'joseph',
    color: '#9a5ad0', dark: '#3a1a5a', skin: '#b87ae8', accent: '#ffe24a',
    glow: 'rgba(170,110,255,0.9)', aura: 'rgba(150,90,230,0.3)', tint: '#6a3aa0',
    stats: { Power: 'D', Speed: 'C', Range: 'D', Durability: 'A', Precision: 'D', Potential: 'E' },
    cry: '', range: 110,
    moves: { J: 'vineWhip', K: 'vineGrab', L: 'hamon' },
    labels: { J: 'Vine Whip', K: 'Vine Grab', L: 'Sunlight Yellow Overdrive' },
    cd: { J: 1.0, K: 5, L: 3 },
    art: { special: 'vines' },
    voice: { pitch: 0.9, rush: '' },
  },
  {
    id: 'the_world', part: 3, name: 'The World', jp: 'ザ・ワールド', user: 'DIO', design: 'dio', pose: 'dio',
    color: '#e0b43a', dark: '#7a5a10', skin: '#f0d27a', accent: '#39a85a',
    glow: 'rgba(255,210,80,0.9)', aura: 'rgba(255,200,60,0.35)', tint: '#b8902a',
    stats: { Power: 'A', Speed: 'A', Range: 'C', Durability: 'A', Precision: 'B', Potential: 'B' },
    cry: 'MUDA', timeMover: true,
    moves: { J: 'barrage', K: 'timeStop', L: 'knives' },
    labels: { J: 'MUDA Rush', K: 'The World (Time Stop)', L: 'Knife Volley' },
    cd: { J: 2.0, K: 16, L: 3.5 },
    tsDur: 5, tsAlt: 'roadRoller', tsCall: 'ZA WARUDO! TOKI WO TOMARE!', resumeCall: 'Toki wa ugoki dasu...',
    art: { head: 'tw', pattern: 'hearts', shoulders: 'heart', lower: 'ghost' },
    voice: { pitch: 1.1, rush: 'muda muda muda muda muda muda muda' },
  },

  // ------------------------------------------------------------------ Part 4
  {
    id: 'crazy_diamond', part: 4, name: 'Crazy Diamond', jp: 'クレイジー・ダイヤモンド', user: 'Josuke Higashikata', design: 'josuke', pose: 'josuke',
    color: '#8fb4e8', dark: '#3f5f96', skin: '#f2a6c8', accent: '#ff7fbf',
    glow: 'rgba(140,190,255,0.9)', aura: 'rgba(255,150,210,0.3)', tint: '#5a78b0',
    stats: { Power: 'A', Speed: 'A', Range: 'D', Durability: 'B', Precision: 'B', Potential: 'C' },
    cry: 'DORA',
    moves: { J: 'barrage', K: 'restore', L: 'punch' },
    labels: { J: 'DORA Rush', K: 'Restore Others', L: 'Heavy Punch' },
    cd: { J: 2.0, K: 6, L: 1.4 },
    art: { head: 'cd', pattern: 'hearts', shoulders: 'heart', lower: 'ghost' },
    voice: { pitch: 1.2, rush: 'dora dora dora dora dora dora dora' },
  },
  {
    id: 'the_hand', part: 4, name: 'The Hand', jp: 'ザ・ハンド', user: 'Okuyasu Nijimura', design: 'okuyasu', pose: 'jolyne',
    color: '#3b5bb5', dark: '#16244a', skin: '#8aa4e8', accent: '#e8c04a',
    glow: 'rgba(120,160,255,0.9)', aura: 'rgba(90,130,240,0.3)', tint: '#2a3a8a',
    stats: { Power: 'B', Speed: 'B', Range: 'D', Durability: 'C', Precision: 'C', Potential: 'C' },
    cry: 'OORA', range: 60,
    moves: { J: 'eraseSwipe', K: 'spacePull', L: 'punch' },
    labels: { J: 'Erase (ガオン)', K: 'Space Pull', L: 'Punch' },
    cd: { J: 1.6, K: 5, L: 1.2 },
    art: { head: 'th', pattern: 'dollar', shoulders: 'pad', lower: 'ghost' },
    voice: { pitch: 0.8, rush: '' },
  },
  {
    id: 'echoes_act3', part: 4, name: 'Echoes ACT3', jp: 'エコーズACT3', user: 'Koichi Hirose', design: 'koichi', pose: 'jolyne',
    color: '#7ec96a', dark: '#2a5a22', skin: '#e8f4e0', accent: '#f2d23a',
    glow: 'rgba(160,255,120,0.9)', aura: 'rgba(140,230,110,0.3)', tint: '#4a8a3a',
    stats: { Power: 'B', Speed: 'B', Range: 'C', Durability: 'B', Precision: 'C', Potential: 'C' },
    cry: 'S-H-I-T', range: 120,
    moves: { J: 'barrage', K: 'threeFreeze', L: 'soundEffect' },
    labels: { J: 'S-H-I-T Rush', K: '3 FREEZE', L: 'ACT2: BOING' },
    cd: { J: 2.0, K: 9, L: 4 },
    barrage: { dmg: 0.9, finisher: { dmg: 14, vx: 1000 } },
    art: { head: 'ec', pattern: 'three', shoulders: 'round', lower: 'ghost', scale: 0.82, slim: true },
    voice: { pitch: 1.4, rush: '' },
  },
  {
    id: 'killer_queen', part: 4, name: 'Killer Queen', jp: 'キラークイーン', user: 'Yoshikage Kira', design: 'kira', pose: 'kira',
    color: '#e8a3c8', dark: '#8a4a6e', skin: '#f3c2dc', accent: '#f4f0e8',
    glow: 'rgba(255,150,210,0.9)', aura: 'rgba(255,140,200,0.35)', tint: '#b0587e',
    stats: { Power: 'A', Speed: 'B', Range: 'D', Durability: 'B', Precision: 'B', Potential: 'A' },
    cry: '',
    moves: { J: 'punch', K: 'bombTouch', L: 'sheerHeartAttack' },
    labels: { J: 'Punch', K: 'First Bomb', L: 'Sheer Heart Attack' },
    cd: { J: 0.9, K: 1.5, L: 10 },
    art: { head: 'kq', pattern: 'skull', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 0.9, rush: '' },
  },
  {
    id: 'heavens_door', part: 4, name: "Heaven's Door", jp: 'ヘブンズ・ドアー', user: 'Rohan Kishibe', design: 'rohan', pose: 'kira',
    color: '#e9d7a8', dark: '#6a5a3a', skin: '#fbf1dc', accent: '#6fbf5a',
    glow: 'rgba(255,240,200,0.9)', aura: 'rgba(250,230,180,0.3)', tint: '#8a7a5a',
    stats: { Power: 'D', Speed: 'B', Range: 'B', Durability: 'D', Precision: 'C', Potential: 'A' },
    cry: '', range: 80,
    moves: { J: 'lightPunch', K: 'bookify', L: 'writeCommand' },
    labels: { J: 'Punch', K: "Heaven's Door", L: 'Write a Command' },
    cd: { J: 0.8, K: 7, L: 3 },
    art: { head: 'hd', pattern: 'none', shoulders: 'round', lower: 'legs', scale: 0.75, slim: true },
    voice: { pitch: 1.3, rush: '' },
  },

  // ------------------------------------------------------------------ Part 5
  {
    id: 'gold_experience', part: 5, name: 'Gold Experience', jp: 'ゴールド・エクスペリエンス', user: 'Giorno Giovanna', design: 'giorno', pose: 'giorno',
    color: '#e8c14a', dark: '#7a5e14', skin: '#f6de8a', accent: '#2f9a5a',
    glow: 'rgba(255,220,90,0.9)', aura: 'rgba(255,210,80,0.35)', tint: '#b8962a',
    stats: { Power: 'C', Speed: 'A', Range: 'C', Durability: 'D', Precision: 'C', Potential: 'A' },
    cry: 'MUDA',
    moves: { J: 'barrage', K: 'lifeGiver', L: 'lifeOverload' },
    labels: { J: 'MUDA Rush', K: 'Life Giver', L: 'Life Overload' },
    cd: { J: 2.0, K: 7, L: 3 },
    art: { head: 'ge', pattern: 'ladybug', shoulders: 'gem', lower: 'ghost' },
    voice: { pitch: 1.2, rush: 'muda muda muda muda muda muda muda' },
  },
  {
    id: 'gold_experience_requiem', part: 5, name: 'Gold Experience Requiem', jp: 'ゴールド・エクスペリエンス・レクイエム', user: 'Giorno Giovanna', design: 'giorno', pose: 'giorno',
    color: '#d9b23a', dark: '#5a4210', skin: '#f8e8a0', accent: '#fff4c0',
    glow: 'rgba(255,240,170,1)', aura: 'rgba(255,230,140,0.45)', tint: '#c0a040',
    stats: { Power: '∞', Speed: '∞', Range: '∞', Durability: '∞', Precision: '∞', Potential: '∞' },
    cry: 'MUDA',
    moves: { J: 'barrage', K: 'returnToZero', L: 'infiniteDeath' },
    labels: { J: 'MUDA Rush', K: 'Return to Zero', L: 'Infinite Death' },
    cd: { J: 1.8, K: 12, L: 10 },
    barrage: { dmg: 1.6, finisher: { dmg: 26, text: 'MUDAAAA!!' } },
    art: { head: 'ger', pattern: 'gold', shoulders: 'gem', lower: 'ghost', scale: 1.2 },
    voice: { pitch: 1.2, rush: 'muda muda muda muda muda muda muda muda' },
  },
  {
    id: 'sticky_fingers', part: 5, name: 'Sticky Fingers', jp: 'スティッキィ・フィンガーズ', user: 'Bruno Bucciarati', design: 'bucciarati', pose: 'giorno',
    color: '#4a6fd0', dark: '#1a2a5a', skin: '#e8ecf6', accent: '#e8c04a',
    glow: 'rgba(110,150,255,0.9)', aura: 'rgba(90,130,240,0.3)', tint: '#3a5ab0',
    stats: { Power: 'A', Speed: 'A', Range: 'C', Durability: 'D', Precision: 'C', Potential: 'D' },
    cry: 'ARI',
    moves: { J: 'barrage', K: 'unzip', L: 'zipTravel' },
    labels: { J: 'ARI ARI Rush', K: 'Zipper', L: 'Zipper Travel' },
    cd: { J: 2.0, K: 4, L: 5 },
    barrage: {
      finisher: { text: 'ARRIVEDERCI!' },
      onHit: (s, b, final) => { if (final && b.kind === 'ragdoll' && Math.random() < 0.5) b.breakJoint(pick(LIMBS), true); },
    },
    art: { head: 'sf', pattern: 'zip', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 1.0, rush: 'ari ari ari ari ari ari arrivederci' },
  },
  {
    id: 'sex_pistols', part: 5, name: 'Sex Pistols', jp: 'セックス・ピストルズ', user: 'Guido Mista', design: 'mista', pose: 'jotaro',
    color: '#f2d23a', dark: '#6a5a10', skin: '#f8e89a', accent: '#f2d23a',
    glow: 'rgba(255,230,90,0.9)', aura: 'rgba(255,220,80,0.3)', tint: '#b09a2a',
    stats: { Power: 'E', Speed: 'C', Range: 'B', Durability: 'C', Precision: 'A', Potential: 'B' },
    cry: '', range: 300,
    moves: { J: 'gunShot', K: 'sixShots', L: 'pistolsKick' },
    labels: { J: 'Revolver Shot', K: 'Six Shooter', L: 'Pistols Kick' },
    cd: { J: 0.6, K: 5, L: 1.5 },
    art: { special: 'pistols' },
    voice: { pitch: 1.0, rush: '' },
  },
  {
    id: 'aerosmith', part: 5, name: 'Aerosmith', jp: 'エアロスミス', user: 'Narancia Ghirga', design: 'narancia', pose: 'jolyne',
    color: '#e8702a', dark: '#6a2a0a', skin: '#f0a060', accent: '#4a9a4a',
    glow: 'rgba(255,140,60,0.9)', aura: 'rgba(255,120,40,0.3)', tint: '#b0501a',
    stats: { Power: 'B', Speed: 'B', Range: 'B', Durability: 'C', Precision: 'E', Potential: 'C' },
    cry: '', range: 280,
    moves: { J: 'machineGun', K: 'radar', L: 'bombDrop' },
    labels: { J: 'Machine Gun', K: 'CO2 Radar', L: 'Bomb Drop' },
    cd: { J: 2.2, K: 8, L: 4 },
    art: { special: 'plane' },
    voice: { pitch: 1.3, rush: '' },
  },
  {
    id: 'purple_haze', part: 5, name: 'Purple Haze', jp: 'パープル・ヘイズ', user: 'Pannacotta Fugo', design: 'fugo', pose: 'kakyoin',
    color: '#9a6ad0', dark: '#3a1a5a', skin: '#e8def2', accent: '#c070ff',
    glow: 'rgba(200,120,255,0.9)', aura: 'rgba(180,100,240,0.35)', tint: '#7a3aa0',
    stats: { Power: 'A', Speed: 'B', Range: 'C', Durability: 'E', Precision: 'E', Potential: 'B' },
    cry: 'UBASHA', range: 90,
    moves: { J: 'barrage', K: 'capsule', L: 'capsuleBurst' },
    labels: { J: 'UBASHA Rush', K: 'Virus Capsule', L: 'Capsule Burst' },
    cd: { J: 2.2, K: 4, L: 12 },
    barrage: { onHit: (s, b, final) => { if (final && b.addStatus) b.addStatus('virus', 3, s.user); } },
    art: { head: 'ph', pattern: 'capsules', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 0.7, rush: '' },
  },
  {
    id: 'king_crimson', part: 5, name: 'King Crimson', jp: 'キング・クリムゾン', user: 'Diavolo', design: 'diavolo', pose: 'diavolo',
    color: '#d8324a', dark: '#6e1020', skin: '#f06070', accent: '#f7e0e4',
    glow: 'rgba(255,60,80,0.9)', aura: 'rgba(255,40,70,0.3)', tint: '#8a1a2a',
    stats: { Power: 'A', Speed: 'A', Range: 'E', Durability: '?', Precision: '?', Potential: '?' },
    cry: '',
    moves: { J: 'chop', K: 'timeErase', L: 'epitaph' },
    labels: { J: 'Chest Chop', K: 'Erase Time', L: 'Epitaph' },
    cd: { J: 1.6, K: 12, L: 4 },
    art: { head: 'kc', pattern: 'net', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 0.6, rush: '' },
  },
  {
    id: 'spice_girl', part: 5, name: 'Spice Girl', jp: 'スパイス・ガール', user: 'Trish Una', design: 'trish', pose: 'kira',
    color: '#f07ab8', dark: '#7a2a5a', skin: '#fbe0ee', accent: '#fbe0ee',
    glow: 'rgba(255,130,200,0.9)', aura: 'rgba(255,120,190,0.35)', tint: '#b04a80',
    stats: { Power: 'A', Speed: 'A', Range: 'C', Durability: 'B', Precision: 'C', Potential: 'A' },
    cry: 'WANNABE',
    moves: { J: 'barrage', K: 'soften', L: 'softGround' },
    labels: { J: 'WANNABE Rush', K: 'Soften', L: 'Soft Ground' },
    cd: { J: 2.0, K: 4, L: 5 },
    art: { head: 'sg', pattern: 'hearts', shoulders: 'heart', lower: 'ghost', slim: true },
    voice: { pitch: 1.5, rush: 'wannabe wannabe wannabe' },
  },

  // ------------------------------------------------------------------ Part 6
  {
    id: 'stone_free', part: 6, name: 'Stone Free', jp: 'ストーン・フリー', user: 'Jolyne Cujoh', design: 'jolyne', pose: 'jolyne',
    color: '#3a8fd0', dark: '#123a5a', skin: '#8fd0f0', accent: '#6ac8ff',
    glow: 'rgba(90,180,255,0.9)', aura: 'rgba(70,160,240,0.3)', tint: '#2a6aa0',
    stats: { Power: 'A', Speed: 'B', Range: 'C', Durability: 'A', Precision: 'C', Potential: 'A' },
    cry: 'ORA',
    moves: { J: 'barrage', K: 'stringWeb', L: 'stringPull' },
    labels: { J: 'ORA Rush', K: 'String Web', L: 'String Pull' },
    cd: { J: 2.0, K: 7, L: 3 },
    art: { head: 'sfree', pattern: 'strings', shoulders: 'round', lower: 'legs' },
    voice: { pitch: 1.4, rush: 'ora ora ora ora ora ora ora' },
  },
  {
    id: 'whitesnake', part: 6, name: 'Whitesnake', jp: 'ホワイトスネイク', user: 'Enrico Pucci', design: 'pucci', pose: 'pucci',
    color: '#e8e8ee', dark: '#3a3a4a', skin: '#f6f6fa', accent: '#8a6ad0',
    glow: 'rgba(240,240,255,0.9)', aura: 'rgba(220,220,240,0.35)', tint: '#6a6a80',
    stats: { Power: '?', Speed: 'D', Range: 'A', Durability: '?', Precision: '?', Potential: '?' },
    cry: '',
    moves: { J: 'punch', K: 'discSteal', L: 'acidFog' },
    labels: { J: 'Punch', K: 'Disc Steal', L: 'Acid Fog' },
    cd: { J: 1.2, K: 8, L: 9 },
    art: { head: 'ws', pattern: 'dna', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 0.8, rush: '' },
  },
  {
    id: 'c_moon', part: 6, name: 'C-MOON', jp: 'C-MOON', user: 'Enrico Pucci', design: 'pucci', pose: 'pucci',
    color: '#5aa84a', dark: '#1a4a1a', skin: '#a8e098', accent: '#f2e87a',
    glow: 'rgba(130,230,110,0.9)', aura: 'rgba(110,210,90,0.35)', tint: '#3a7a2a',
    stats: { Power: '?', Speed: 'B', Range: 'B', Durability: '?', Precision: '?', Potential: '?' },
    cry: '',
    moves: { J: 'insideOut', K: 'gravityPush', L: 'gravityFlip' },
    labels: { J: 'Inside-Out Punch', K: 'Gravity Repulsion', L: 'Gravity Reversal' },
    cd: { J: 1.6, K: 5, L: 8 },
    art: { head: 'cm', pattern: 'moon', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 0.8, rush: '' },
  },
  {
    id: 'made_in_heaven', part: 6, name: 'Made in Heaven', jp: 'メイド・イン・ヘブン', user: 'Enrico Pucci', design: 'pucci', pose: 'pucci',
    color: '#f0f0f4', dark: '#2a2a3a', skin: '#fafaff', accent: '#e8c04a',
    glow: 'rgba(255,255,255,1)', aura: 'rgba(240,240,255,0.4)', tint: '#8a8aa0',
    stats: { Power: 'B', Speed: '∞', Range: 'A', Durability: 'A', Precision: 'C', Potential: 'A' },
    cry: '',
    moves: { J: 'barrage', K: 'accelerate', L: 'blitz' },
    labels: { J: 'Accelerated Rush', K: 'Time Acceleration', L: 'Speed Blitz' },
    cd: { J: 1.6, K: 22, L: 3 },
    barrage: { interval: 0.03, dmg: 1.1, cry: '', finisher: { text: 'MADE IN HEAVEN' } },
    art: { head: 'mih', pattern: 'clock', shoulders: 'round', lower: 'horse' },
    voice: { pitch: 0.8, rush: '' },
  },

  // ------------------------------------------------------------------ Part 7
  {
    id: 'tusk_act4', part: 7, name: 'Tusk ACT4', jp: 'タスクACT4', user: 'Johnny Joestar', design: 'johnny', pose: 'jotaro',
    color: '#e6a0c4', dark: '#6a2a4a', skin: '#fbe4f0', accent: '#f2d23a',
    glow: 'rgba(255,170,220,0.9)', aura: 'rgba(250,150,210,0.35)', tint: '#a05080',
    stats: { Power: 'A', Speed: 'B', Range: 'E', Durability: 'A', Precision: 'A', Potential: '?' },
    cry: 'ORA', range: 200,
    moves: { J: 'nailShot', K: 'infiniteRotation', L: 'barrage' },
    labels: { J: 'Nail Shot', K: 'Infinite Rotation', L: 'ORA Rush' },
    cd: { J: 0.8, K: 10, L: 2.2 },
    art: { head: 'tusk', pattern: 'horseshoe', shoulders: 'star', lower: 'legs' },
    voice: { pitch: 1.1, rush: 'ora ora ora ora ora ora' },
  },
  {
    id: 'd4c', part: 7, name: 'Dirty Deeds Done Dirt Cheap', jp: 'いともたやすく行われるえげつない行為', user: 'Funny Valentine', design: 'valentine', pose: 'pucci',
    color: '#6a8fd6', dark: '#1a2a5a', skin: '#e8eefa', accent: '#fff6a0',
    glow: 'rgba(130,170,255,0.9)', aura: 'rgba(110,150,240,0.35)', tint: '#3a5aa0',
    stats: { Power: 'A', Speed: 'A', Range: 'C', Durability: 'A', Precision: 'A', Potential: 'A' },
    cry: '',
    moves: { J: 'punch', K: 'clone', L: 'dimensionHop' },
    labels: { J: 'Punch', K: 'Parallel World Clone', L: 'Dimension Hop' },
    cd: { J: 1.2, K: 16, L: 4 },
    art: { head: 'd4c', pattern: 'none', shoulders: 'round', lower: 'ghost' },
    voice: { pitch: 0.9, rush: '' },
  },

  // ------------------------------------------------------------------ Part 8
  {
    id: 'soft_and_wet', part: 8, name: 'Soft & Wet', jp: 'ソフト＆ウェット', user: 'Josuke Higashikata (JoJolion)', design: 'gappy', pose: 'josuke',
    color: '#f0e6ee', dark: '#6a4a6a', skin: '#fbf4fa', accent: '#ff8fc8',
    glow: 'rgba(255,220,240,0.9)', aura: 'rgba(250,210,240,0.35)', tint: '#a07aa0',
    stats: { Power: 'A', Speed: 'B', Range: 'C', Durability: 'A', Precision: 'C', Potential: 'A' },
    cry: 'ORA',
    moves: { J: 'barrage', K: 'bubbleFriction', L: 'bubbleSight' },
    labels: { J: 'ORA Rush', K: 'Plunder: Friction', L: 'Plunder: Sight' },
    cd: { J: 2.0, K: 3, L: 6 },
    art: { head: 'sw', pattern: 'bubbles', shoulders: 'star', lower: 'ghost' },
    voice: { pitch: 1.1, rush: 'ora ora ora ora ora ora' },
  },
];

const STAND_DEFS = {};
for (const d of STAND_LIST) {
  d.partName = PARTS[d.part];
  d.voice = d.voice || { pitch: 1, rush: '' };
  d.art = d.art || {};
  d.range = d.range || 55;
  STAND_DEFS[d.id] = d;
}
const STAND_KEYS = Object.keys(STAND_DEFS);
